Adding telephone to the contact us page
TravisAndLeo/HawkWingForge pull request #4
Opened 2017-03-21 02:01 UTC by LeoTanoue

Adding telephone to the contact us page after reviewing the page with Evan. That page is ready to phase 1 roll out!

2017-03-21 12:37 UTC, travv0 requested changes
There's a typo in the label

2017-03-21 12:37 UTC, tssund93 commented on src/HawkWingForge/Views/Home/Contact.cshtml
> +                <label for="name">Telehpone</label>
Typo

2017-03-22 04:32 UTC, LeoTanoue commented
Typo fixed!

2017-03-22 11:29 UTC, travv0 approved these changes

2017-04-13 02:14 UTC, merged